org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

mod_version=3.0.0+mc-26.3-port
maven_group=coopmod.example
archives_base_name=dap-ur-homies

fabric_api_version=0.162.0+26.3
pal_version=1.2.8+mc.26.3
