package com.cooptest;

import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.sounds.SoundEvent;

public class ModSounds {
   public static final Identifier EPIC_DAP_ID = Identifier.fromNamespaceAndPath("testcoop", "epic_dap");
   public static final SoundEvent EPIC_DAP = SoundEvent.createVariableRangeEvent(EPIC_DAP_ID);
   public static final Identifier EXPLOSION_IMPACT_ID = Identifier.fromNamespaceAndPath("testcoop", "explosion_impact");
   public static final SoundEvent EXPLOSION_IMPACT = SoundEvent.createVariableRangeEvent(EXPLOSION_IMPACT_ID);
   public static final Identifier MAHITO_ID = Identifier.fromNamespaceAndPath("testcoop", "mahito");
   public static final SoundEvent MAHITO = SoundEvent.createVariableRangeEvent(MAHITO_ID);
   public static final Identifier GALACTIC_DAP_ID = Identifier.fromNamespaceAndPath("testcoop", "galactic_dap");
   public static final SoundEvent GALACTIC_DAP = SoundEvent.createVariableRangeEvent(GALACTIC_DAP_ID);
   public static final Identifier TRUE_FRIENDSHIP_ID = Identifier.fromNamespaceAndPath("testcoop", "true_friendship");
   public static final SoundEvent TRUE_FRIENDSHIP = SoundEvent.createVariableRangeEvent(TRUE_FRIENDSHIP_ID);
   public static final Identifier IMPACT_ID = Identifier.fromNamespaceAndPath("testcoop", "impact");
   public static final SoundEvent IMPACT = SoundEvent.createVariableRangeEvent(IMPACT_ID);
   public static final Identifier MARIO_JUMP_ID = Identifier.fromNamespaceAndPath("testcoop", "mariojump");
   public static final SoundEvent MARIO_JUMP = SoundEvent.createVariableRangeEvent(MARIO_JUMP_ID);
   public static final SoundEvent FIRE_IMPACT = SoundEvent.createVariableRangeEvent(Identifier.fromNamespaceAndPath("testcoop", "fireimpact"));
   public static final Identifier DAP_MISS_ID = Identifier.fromNamespaceAndPath("testcoop", "dap.miss");
   public static final SoundEvent DAP_MISS = SoundEvent.createVariableRangeEvent(DAP_MISS_ID);
   public static final Identifier DAP_WEAK_ID = Identifier.fromNamespaceAndPath("testcoop", "dap.weak");
   public static final SoundEvent DAP_WEAK = SoundEvent.createVariableRangeEvent(DAP_WEAK_ID);
   public static final Identifier SNAP_ID = Identifier.fromNamespaceAndPath("testcoop", "snap");
   public static final SoundEvent SNAP = SoundEvent.createVariableRangeEvent(SNAP_ID);
   public static final Identifier DAP_HIT_ID = Identifier.fromNamespaceAndPath("testcoop", "dap.hit");
   public static final SoundEvent DAP_HIT = SoundEvent.createVariableRangeEvent(DAP_HIT_ID);
   public static final Identifier SLAP_ID = Identifier.fromNamespaceAndPath("testcoop", "slap");
   public static final SoundEvent SLAP = SoundEvent.createVariableRangeEvent(SLAP_ID);
   public static final Identifier TORTURE_ID = Identifier.fromNamespaceAndPath("testcoop", "totrute");
   public static final SoundEvent TORTURE = SoundEvent.createVariableRangeEvent(TORTURE_ID);
   public static final Identifier FAHH_ID = Identifier.fromNamespaceAndPath("testcoop", "fahh");
   public static final SoundEvent FAHH = SoundEvent.createVariableRangeEvent(FAHH_ID);
   public static final Identifier CLAP_SWAP_ID = Identifier.fromNamespaceAndPath("testcoop", "clap_swap");
   public static final SoundEvent CLAP_SWAP = SoundEvent.createVariableRangeEvent(CLAP_SWAP_ID);
   public static final Identifier PERFECT_DAP_ID = Identifier.fromNamespaceAndPath("testcoop", "cooldap");
   public static final SoundEvent PERFECT_DAP = SoundEvent.createVariableRangeEvent(PERFECT_DAP_ID);
   public static final Identifier CLEAN_DAP_ID = Identifier.fromNamespaceAndPath("testcoop", "clean_dap");
   public static final SoundEvent CLEAN_DAP = SoundEvent.createVariableRangeEvent(CLEAN_DAP_ID);
   public static final Identifier CLEAN_DAP_2_ID = Identifier.fromNamespaceAndPath("testcoop", "clean_dap2");
   public static final SoundEvent CLEAN_DAP_2 = SoundEvent.createVariableRangeEvent(CLEAN_DAP_2_ID);
   public static final Identifier DAP_FOLLOW_ID = Identifier.fromNamespaceAndPath("testcoop", "dap_follow");
   public static final SoundEvent DAP_FOLLOW = SoundEvent.createVariableRangeEvent(DAP_FOLLOW_ID);
   public static final Identifier AURA_ID = Identifier.fromNamespaceAndPath("testcoop", "aura");
   public static final SoundEvent AURA = SoundEvent.createVariableRangeEvent(AURA_ID);
   public static final Identifier HELI_ID = Identifier.fromNamespaceAndPath("testcoop", "heli");
   public static final SoundEvent HELI = SoundEvent.createVariableRangeEvent(HELI_ID);
   public static final SoundEvent CLAP_1 = SoundEvent.createVariableRangeEvent(Identifier.fromNamespaceAndPath("testcoop", "clap1"));
   public static final SoundEvent CLAP_2 = SoundEvent.createVariableRangeEvent(Identifier.fromNamespaceAndPath("testcoop", "clap2"));
   public static final SoundEvent CLAP_3 = SoundEvent.createVariableRangeEvent(Identifier.fromNamespaceAndPath("testcoop", "clap3"));
   public static final SoundEvent CLAP_4 = SoundEvent.createVariableRangeEvent(Identifier.fromNamespaceAndPath("testcoop", "clap4"));
   public static final SoundEvent CLAP_5 = SoundEvent.createVariableRangeEvent(Identifier.fromNamespaceAndPath("testcoop", "clap5"));
   public static final SoundEvent CLAP_6 = SoundEvent.createVariableRangeEvent(Identifier.fromNamespaceAndPath("testcoop", "clap6"));
   public static final SoundEvent[] CLAP_SOUNDS = new SoundEvent[]{CLAP_1, CLAP_2, CLAP_3, CLAP_4, CLAP_5, CLAP_6};

   public static void register() {
      Registry.register(BuiltInRegistries.SOUND_EVENT, EPIC_DAP_ID, EPIC_DAP);
      Registry.register(BuiltInRegistries.SOUND_EVENT, EXPLOSION_IMPACT_ID, EXPLOSION_IMPACT);
      Registry.register(BuiltInRegistries.SOUND_EVENT, MAHITO_ID, MAHITO);
      Registry.register(BuiltInRegistries.SOUND_EVENT, GALACTIC_DAP_ID, GALACTIC_DAP);
      Registry.register(BuiltInRegistries.SOUND_EVENT, TRUE_FRIENDSHIP_ID, TRUE_FRIENDSHIP);
      Registry.register(BuiltInRegistries.SOUND_EVENT, IMPACT_ID, IMPACT);
      Registry.register(BuiltInRegistries.SOUND_EVENT, MARIO_JUMP_ID, MARIO_JUMP);
      Registry.register(BuiltInRegistries.SOUND_EVENT, Identifier.fromNamespaceAndPath("testcoop", "fireimpact"), FIRE_IMPACT);
      Registry.register(BuiltInRegistries.SOUND_EVENT, DAP_MISS_ID, DAP_MISS);
      Registry.register(BuiltInRegistries.SOUND_EVENT, DAP_WEAK_ID, DAP_WEAK);
      Registry.register(BuiltInRegistries.SOUND_EVENT, SNAP_ID, SNAP);
      Registry.register(BuiltInRegistries.SOUND_EVENT, DAP_HIT_ID, DAP_HIT);
      Registry.register(BuiltInRegistries.SOUND_EVENT, SLAP_ID, SLAP);
      Registry.register(BuiltInRegistries.SOUND_EVENT, TORTURE_ID, TORTURE);
      Registry.register(BuiltInRegistries.SOUND_EVENT, FAHH_ID, FAHH);
      Registry.register(BuiltInRegistries.SOUND_EVENT, CLAP_SWAP_ID, CLAP_SWAP);
      Registry.register(BuiltInRegistries.SOUND_EVENT, HELI_ID, HELI);
      Registry.register(BuiltInRegistries.SOUND_EVENT, CLEAN_DAP_ID, CLEAN_DAP);
      Registry.register(BuiltInRegistries.SOUND_EVENT, CLEAN_DAP_2_ID, CLEAN_DAP_2);
      Registry.register(BuiltInRegistries.SOUND_EVENT, DAP_FOLLOW_ID, DAP_FOLLOW);
      Registry.register(BuiltInRegistries.SOUND_EVENT, Identifier.fromNamespaceAndPath("testcoop", "clap1"), CLAP_1);
      Registry.register(BuiltInRegistries.SOUND_EVENT, Identifier.fromNamespaceAndPath("testcoop", "clap2"), CLAP_2);
      Registry.register(BuiltInRegistries.SOUND_EVENT, Identifier.fromNamespaceAndPath("testcoop", "clap3"), CLAP_3);
      Registry.register(BuiltInRegistries.SOUND_EVENT, Identifier.fromNamespaceAndPath("testcoop", "clap4"), CLAP_4);
      Registry.register(BuiltInRegistries.SOUND_EVENT, Identifier.fromNamespaceAndPath("testcoop", "clap5"), CLAP_5);
      Registry.register(BuiltInRegistries.SOUND_EVENT, Identifier.fromNamespaceAndPath("testcoop", "clap6"), CLAP_6);
   }
}
